application: bro-chan
version: production
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.git/.*)|
 (chan\.iml)|
 (\.idea/.*)|
 )$

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on
- appstats: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static/\d+/css/([^/].*)\.css
  static_files: static/css/\1.css
  upload: static/css/([^/].*)\.css

- url: /static/\d+/img/([^/].*)
  static_files: static/img/\1
  upload: static/img/([^/].*)

- url: /static/\d+/js/([^/].*)
  static_files: static/js/\1
  upload: static/js/([^/].*)

- url: /login
  script: main.app

- url: /logout
  script: main.app

- url: /new-thread/.+
  script: main.app

- url: /post/\d+
  script: main.app

- url: /post/\d+/reply/.+
  script: main.app

- url: /image/\d+
  script: main.app

- url: /admin/post/\d+/ban(delete)?
  script: main.app

- url: /admin/ban
  script: main.app

- url: /tasks/expire
  script: main.app
  login: admin

- url: /
  script: main.app

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /.*
  static_files: static/404.html
  upload: static/404\.html
  expiration: "0s"